### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by joaocampinhos** [joaocampinhos/CIAI#1]
# TODO
- [x] Login
- [x] Registos
- [x] BCrypt (fácil)
- [x] Limitar edits/creates/deletes nos vários recursos com o método dos profs (pode ser visto [aqui](https://bitbucket.org/jacome/iadi/branch/basic_security#diff))
- [x] Usar o utilizador corrente em vez de um default para cada dashboard
- [x] Mostrar algures na página o nome do utilizador corrente
